---
abstract: 'Fast and featureful data structure validation'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Data::Dump::OneLine: 0
  File::ShareDir::Tarball: 0
  File::Slurp: 0
  File::Which: 0
  File::chdir: 0
  Module::Build: 0.3601
  Sah: v0.9.25
  Test::Exception: 0
  Test::More: 0.98
  Test::Warn: 0
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Sah
requires:
  Algorithm::Dependency::Ordered: 0
  Algorithm::Dependency::Source::HoA: 0
  Data::Clean::JSON: 0
  Data::ModeMerge: 0.21
  JSON: 0
  Language::Expr: 0.13
  Language::Expr::Interpreter::VarEnumer: 0.13
  Lingua::EN::Numbers::Ordinate: 1.02
  Log::Any: 0.09
  Module::Path: 0.08
  Moo: 0
  Moo::Role: 0
  SHARYANTO::String::Util: 0
  Sub::Install: 0
  Text::sprintfn: 0
  Tie::IxHash: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Data-Sah/
  repository: http://github.com/sharyanto/perl-Data-Sah
version: 0.16
