---
abstract: 'Schema for data structures'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::chdir: 0
  Module::Build: 0.3601
  Test::Aggregate: 0
  Test::Exception: 0
  Test::More: 0.96
  YAML::Syck: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Sah
requires:
  Algorithm::Dependency: 0
  Class::Inspector: 0
  Data::Clone: 0
  Data::Dump::OneLine: 0.02
  Data::ModeMerge: 0.21
  DateTime: 0
  DateTime::Format::ISO8601: 0
  Digest::MD5: 0
  Language::Expr: 0.13
  List::MoreUtils: 0
  Log::Any: 0.09
  Moo: 0
  Regexp::Grammars: 0
  SHARYANTO::Role::I18NMany: 0
  Scalar::Util: 0
  Sub::Install: 0
  URI::Escape: 0
  boolean: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Data-Sah/
  repository: http://github.com/sharyanto/perl-Data-Sah
version: 0.03
