package Data::Sah::Manual::Translation; # just to make PodWeaver happy

our $VERSION = '0.08'; # VERSION

1;
# ABSTRACT: Translating Sah messages


__END__
=pod

=head1 NAME

Data::Sah::Manual::Translation - Translating Sah messages

=head1 VERSION

version 0.08

=head1 DESCRIPTION

This document explains how to translate messages in Sah.

=head1 TRANSLATING THE HUMAN COMPILER

=head1 CUSTOM ERROR MESSAGES

=head1 AUTHOR

Steven Haryanto <stevenharyanto@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Steven Haryanto.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut

